(loop for (mode . ext) in '((emacs-lisp-mode . "\\.el$")
                            (lisp-mode . "\\.\\(cl\\|lisp\\)$")
                            (scheme-mode . "\\.scm$")
                            (clojure-mode . "\\.clj$")
                            (perl-model . "\\.\\(pl\\|t\\|psgi\\)$")
                            (go-mode . "\\.go$")
                            (yaml-mode . "\\.ya?ml$")
                            (js2-mode . "\\.js$")
                            (coffee-mode . "\\.coffee$")
                            (ruby-mode . "\\.rb$")
                            (org-mode . "\\.org$")
                            (css-mode . "\\.css$")
                            (less-css-mode . "\\.less$")
                            (markdown-mode . "\\.\\(md\\|markdown\\)$")
                            (html-mode . "\\.\\(html\\|htm\\|emb\\|tmpl\\|tt\\)$")
                            (hatena-diary-mode . "\\.htn$"))
      do (add-to-list 'auto-mode-alist (cons ext mode)))
