(require-or-install 'anything)
(require-or-install 'anything-startup)
(global-set-key (kbd "C-x C-f") 'anything-find-file)
(global-set-key (kbd "C-x b") 'anything)
(global-set-key (kbd "M-x") 'anything-execute-extended-command)
(define-key anything-map "\C-j" 'anything-next-line)
(define-key anything-map "\C-k" 'anything-previous-line)
(define-key anything-map "\M-j" 'anything-next-page)
(define-key anything-map "\M-k" 'anything-previous-page)
